configuration:
  working_directory: "/data/youtube"
  log_level: "INFO"
  max_download_speed: "10M"
  file_name_max_bytes: 255

presets:
  # YouTube Music Preset
  music_preset:
    output_options:
      output_directory: "/data/youtube/music/{uploader}"
      file_name: "{upload_date} - {title}.{ext}"
      thumbnail_name: "{upload_date} - {title}.{thumbnail_ext}"
    ytdl_options:
      format: "bestaudio/best"
      writesubtitles: False
      writeautomaticsub: False
      subtitleslangs: 
        - "en"
      ignoreerrors: True
      extract_flat: False
    
  # Channel Content Preset  
  channel_preset:
    output_options:
      output_directory: "/data/youtube/channels/{uploader}"
      file_name: "{upload_date} - {title}.{ext}"
      thumbnail_name: "{upload_date} - {title}.{thumbnail_ext}"
    ytdl_options:
      format: "best[height<=1080]/bestvideo[height<=1080]+bestaudio/best"
      writesubtitles: True
      writeautomaticsub: True
      subtitleslangs:
        - "en"
      ignoreerrors: True
      extract_flat: False
      
  # Playlist Preset
  playlist_preset:
    output_options:
      output_directory: "/data/youtube/playlists/{playlist_title}"
      file_name: "{playlist_index:0>3d} - {title}.{ext}"
      thumbnail_name: "{playlist_index:0>3d} - {title}.{thumbnail_ext}"
    ytdl_options:
      format: "best[height<=1080]/bestvideo[height<=1080]+bestaudio/best"
      writesubtitles: True
      writeautomaticsub: True
      subtitleslangs:
        - "en"
      ignoreerrors: True
      extract_flat: False

# Multi-User Subscriptions Configuration
# Separate configs for different family members

subscriptions:
  # Admin/Parent content
  admin_content:
    preset: "channel_preset"
    config_file: "admin_creators.yaml"
    output_directory: "/data/youtube/admin"
    
  # Family shared content
  family_content:
    preset: "channel_preset"
    config_file: "family_creators.yaml"
    output_directory: "/data/youtube/family"
    
  # Kids content
  kids_content:
    preset: "channel_preset"
    config_file: "kids_creators.yaml"
    output_directory: "/data/youtube/kids"
    
  # Teen content
  teen_content:
    preset: "channel_preset"
    config_file: "teen_creators.yaml"
    output_directory: "/data/youtube/teen"
    
  # Shared music
  music_content:
    preset: "music_preset"
    config_file: "music_creators.yaml"
    output_directory: "/data/youtube/music"

# Optional: NFO file generation for Jellyfin
nfo_tags:
  tags:
    - "YouTube"
    - "Internet Content"
  genres:
    - "Web Series"
    - "Educational"
  network: "YouTube"