# Jellyfin YouTube Integration Configuration

jellyfin:
  server_url: "http://jellyfin:8096"
  api_key: "${JELLYFIN_API_KEY}"  # Set in environment or .env file
  library_path: "/data/media/youtube"
  
  # Multi-User Library organization
  libraries:
    # Admin/Parent Content
    admin_youtube:
      name: "Admin YouTube"
      path: "/data/media/youtube/admin"
      content_type: "movies"
      
    # Family Shared Content  
    family_youtube:
      name: "Family YouTube"
      path: "/data/media/youtube/family"
      content_type: "movies"
      
    # Kids Content
    kids_youtube:
      name: "Kids YouTube"
      path: "/data/media/youtube/kids"
      content_type: "movies"
      
    # Teen Content
    teen_youtube:
      name: "Teen YouTube"
      path: "/data/media/youtube/teen"
      content_type: "movies"
      
    # Shared Music
    youtube_music:
      name: "YouTube Music"
      path: "/data/media/youtube/music"
      content_type: "music"
      
  # Metadata settings
  metadata:
    generate_nfo: true
    include_thumbnails: true
    include_descriptions: true
    include_upload_date: true
    include_view_count: false
    include_like_count: false
    
  # Collection management
  collections:
    create_channel_collections: true
    create_category_collections: true
    create_date_collections: false
    
# Integration settings
integration:
  auto_scan_interval: 3600  # seconds (1 hour)
  batch_size: 10
  concurrent_downloads: 2
  retry_attempts: 3
  retry_delay: 30  # seconds
  
  # File naming
  naming:
    videos: "{upload_date} - {title}"
    music: "{uploader} - {title}"
    playlists: "{playlist_index:0>3d} - {title}"
    
  # Quality preferences per content type
  quality:
    videos: "1080p"
    music: "audio_only"
    live_streams: "720p"
    
# Notification settings
notifications:
  enabled: true
  events:
    - "download_complete"
    - "library_updated" 
    - "error_occurred"
    
  ntfy:
    server: "${NTFY_SERVER}"
    topic: "${NTFY_TOPIC_SUMMARY}"
    
# Cleanup settings
cleanup:
  old_files:
    enabled: true
    retention_days: 180  # Keep files for 6 months
    
  failed_downloads:
    enabled: true
    cleanup_after_days: 7
    
  temp_files:
    enabled: true
    cleanup_after_hours: 24
    
# Logging
logging:
  level: "INFO"
  file: "/var/log/homelab-shv/jellyfin-youtube.log"
  max_size_mb: 50
  backup_count: 5